# Generated by Django 6.0.1 on 2026-01-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_item_description_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='position',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='position',
            name='occupied',
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.position')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.position')),
            ],
            options={
                'unique_together': {('item', 'position')},
            },
        ),
    ]
