# Generated by Django 6.0.1 on 2026-01-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_item_position_remove_item_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_out', to='storage.position')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item')),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_in', to='storage.position')),
            ],
        ),
    ]
